spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3309/test?characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://127.0.0.1:3309/dn3?characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://127.0.0.1:3309/dn3?characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.pw.example.demo1.controller: 'off'
